name: Lint using Flake8

on: [push]

env:
  PYTHON_VERSION: 3.8.5

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.4
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}